### PR TITLE
[KR] changed minor errors

### PR DESCRIPTION
**Pull request by eugene-renoir**

### CODE REVIEW

**Comment by eugene-renoir** [comment]
@Atcold I see. Can I close this pull request? I will re-fork the repository and then open a pull request again with no changed encoding and edit (after correct some minor errors).

**Comment by Atcold** [comment]
There's no need to re-fork. Just put back the file in the original encoding, commit, and push.

**Comment by eugene-renoir** [comment]
@Atcold First of all, I apologize to you about my mistake.. I closed the pull request. Is this closing work as same as reverting the changed files? Or should I have to revert my commit? I tried to delete my forked pytorch-Deep-Learning repository, but I couldn't do that. I could not delete the repository as well as my other repositories (I cannot delete them, too) ... I have no idea why this is happening.

**Comment by Atcold** [comment]
I didn't merge your PR.
I believe you changed the encoding of the files. All I was asking was to submit your edits without changing the file encoding, so that we could verify what your contribution is.
Now, do you still have the edits you wanted to push?

**Pull request closed without merging**
