### PR TITLE
Minor fix in 01-tensor_tutorial.ipynb

### PR DESCRIPTION
**Pull request by jayantkashyap**
Hi Alfredo, 
Just started a hands-on on these notebooks. Came across this minor fix. Please have a look.

Thanks!

### CODE REVIEW

**Review by Atcold — APPROVED** [review]
Thank you!

**Comment by webdevserv** [comment]
Ciao Alfredo,
Just following this notebook, thank you.  Almost at the end I encounter a 
      1 # Set default plots
----> 2 from res.plot_lib import set_default
      3 from matplotlib import pyplot as plt
      4 set_default()

ModuleNotFoundError: No module named 'res'

Gracie.

I have the following installed.

Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (1.13.1+cu116)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch) (4.4.0)

**Comment by webdevserv** [comment]
My environment.  All running in google colab platform with the following confirmed. 

Tensor Flow Version: 2.9.2
Keras Version: 2.9.0

Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Pandas 1.3.5
Scikit-Learn 1.0.2
GPU is available****

**Comment by webdevserv** [comment]
the plots work now I have to comment out these two (running on google colab environment with miniconda isntalled)
# Set default plots
#from res.plot_lib import set_default
from matplotlib import pyplot as plt
#set_default()

**Comment by Atcold** [comment]
@webdevserv, what does this even mean?

> running on google colab environment with miniconda installed

You either run it on Colab or on your local device.
You're commenting out an import statement and a function defined in the external file.

**Pull request merged**
