### PR TITLE
[JA] review and modify week01, week02, week06, week07, week08, week09, week10, week11, week12, week13, week14, index.md and README-JA.md & some modifications & irrelevant files

### PR DESCRIPTION
**Pull request by t46**
I reviewed and modified week06. While rebasing on `upstream master`,  I changed some files by mistake but the content of the file does not change. Because the contents of these files are the same as those in `upstream master`, I think these will not harm the project. So sorry for bothering you with such a mistake. If there is any inconvenience, let me know, I'll soon fix it up. 

The main commits are following:

docs/ja/week01/
docs/ja/week02/
docs/ja/week06/
docs/ja/week07/
docs/ja/week08/
docs/ja/week09/
docs/ja/week10/
docs/ja/week11/
docs/ja/week12/
docs/ja/week13/
docs/ja/week14/
index.md
README-JA.md

Some modifications are done for the following files:

docs/ja/week03/03-1.md
docs/ja/week03/03-2.md
docs/ja/week04/04-1.md
docs/ja/week12/12-2.md

The others are irrelevant commits: changed by mistake but the content is the same.

Thanks

### CODE REVIEW

**Comment by Atcold** [comment]
I just got notified about this (20 days ago).
I'm a little confused why it wasn't merged before.

**Comment by Atcold** [comment]
Hello @t46, can you give me some feedback?

**Comment by t46** [comment]
I think this PR was not merged just because this was not checked by any reviewers. But I think that is ready to be merged.  Sorry for the messed up PR since I created this when I started GitHub.

**Review by Atcold — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
