### PR TITLE
Scribe notes week 12 section 3

### PR DESCRIPTION
**Pull request by fg746**
Upload collective scribe notes to 12-3.md, upload images, and update _config.yml

### CODE REVIEW

**Comment by Atcold** [comment]
Thanks! Please, add summary to `12.md` as well, commit, and push.

**Comment by fg746** [comment]
Added summary to 12.md

**Comment by Atcold** [comment]
Screenshot 2020-05-01 at 22 51 30
 Please, fix.

**Comment by Atcold** [comment]
I fixed most of it.
Please, refork (or check out the new master) and fix the few bugs left.
Thanks.

Screenshot 2020-05-01 at 23 04 19

**Comment by fg746** [comment]
Thanks, I will fix these now!

**Comment by Atcold** [comment]
You may want to run the website locally, so that you can check stuff actually renders.

**Pull request merged**
