### PR TITLE
[AR] Translation (02-1, 02-2, 02-3) + Review (index, 01-3, 02, 03-2, 03-3, 04-1, 05-2, 05-3, 06, 06-1, 14-2)

### PR DESCRIPTION
**Pull request by hayaalsh**

### CODE REVIEW

**Comment by hayaalsh** [comment]
I am going to close the pull request as I want to record a video on the translation process starting from forking the repo to submitting a PR for the Arabic translation team. I will commit all the changes as soon as I am done.

**Comment by Atcold** [comment]
I didn't understand what does the video have to do with this PR.

**Comment by hayaalsh** [comment]
I wanted to contribute to the team by recording a video for translators with no GH experience explaining the steps in details including starting a PR from scratch. I wasn’t able to do that as I had this preexisting open PR. Closing it was the fastest way to go. A new PR was opened after recording the video containing everything here along with new reviews of other files. I hope this addresses your comment and clarify any confusion.

**Comment by hayaalsh** [comment]
Also, I’m very happy to see you back!! 🤩

**Comment by Atcold** [comment]
Yeah, I've been rather busy with this year's edition of the course.
I'm trying to push out the new videos, which somehow similar but different from last year.

**Pull request closed without merging**
