### PR TITLE
[IT] Translation of 06 

### PR DESCRIPTION
**Pull request by synchro--**
This PR completes the 06 week, adding the italian translation of 

- 06-2.md 
- 06-3.md (WIP, NB. figures and titles are complete, text is wip, due for tomorrow)

### CODE REVIEW

**Comment by Atcold** [comment]
Hi @synchro-- can you specify what day is "tomorrow"?
I see the top message being updated 5 days ago, and the last commit from 9 days ago.
"tomorrow" should have been 4 days ago, but there is no commit with that time stamp.
So, I take it's still WIP?

**Comment by synchro--** [comment]
Yeah it's wip, I wanted to send it Tuesday cause it's almost done but I had no occasion to work on it in these days, sadly.

**Comment by synchro--** [comment]
@Atcold it's 2Am of a Sunday but it's ready2review :)

**Comment by synchro--** [comment]
> Great! I've updated `docs/_config.yml` for you.

Thanks man!

**Pull request merged**
