### PR TITLE
fixing bugs

### PR DESCRIPTION
**Pull request by fg746**
Rendered the webpage from my forked repo and it looks good. Sorry for the many bugs -- first time using KateX!

### CODE REVIEW

**Comment by Atcold** [comment]
Sweet, thanks!
What was the major issue? Just a few missing spaces?

**Comment by fg746** [comment]
The main issue was with subscripting and superscripting the equation in curly braces. I wanted to write something like "{x} from i=1 to t" and realized you need an extra \ before the subscript _. 

$\lbrace x \rbrace_{i=1}^t$ --> $\lbrace x \rbrace\_{i=1}^t$

The former shows up fine on hackDM, the latter works on the website.

**Comment by Atcold** [comment]
I think you wrote the same thing? Or I am blind (which could also be).

**Comment by fg746** [comment]
Markdown automatic styling on the comments removed the difference 😅. Now you can see there is an extra \ before the _. Very small bug that messed up a whole paragraph.

**Comment by Atcold** [comment]
Wow! For real?! How did you figure it out?
Also, you can use `code mode` to disable that, here on GitHub.

**Pull request merged**
