### PR TITLE
[ZH] Fixing 13-3.

### PR DESCRIPTION
**Pull request by JonathanSum**
https://github.com/Atcold/pytorch-Deep-Learning/issues/618

This Pull request should be closed. I tried to fix the issue for https://github.com/Atcold/pytorch-Deep-Learning/issues/618
by replacing the latex form the English file. But it looks like the GitHub thinks the latex is the same as the English version. I added a space to make GitHub thinks they are different. If after pulling this requestion and shows the issue is not fixed. It means the issue is not in the translated Chinese file.

### CODE REVIEW

**Comment by Atcold** [comment]
What am I supposed to do with this PR?

**Comment by JonathanSum** [comment]
I guess the reason why the latex is broke is the front type:

It is either the first one is from the English version or the Chinese version, but you can see they are different.

$\lbrace\boldsymbol{x}_{i}\rbrace^{t}{i=1}$
$\lbrace\boldsymbol{x}_{i}\rbrace^{t}{i=1}$

$\boldsymbol{h}$
$\boldsymbol{h}$

$\boldsymbol{X}\boldsymbol{a}$
$\boldsymbol{X}\boldsymbol{a}$

$\boldsymbol{a}$
$\boldsymbol{a}$

$\boldsymbol{x}{i}$
$\boldsymbol{x}{i}$

If after you merged it and the latex issue remains, I don't know what to do.

**Comment by JonathanSum** [comment]
I will follow this pull request as a guideline to fix it by Sunday or next Monday.
https://github.com/Atcold/pytorch-Deep-Learning/pull/576

**Comment by JonathanSum** [comment]
I have added little changes on Chinese to improve its translation, but the Latex is still the same as the English one.
The Chinese version is using this as the English one: $\boldsymbol{x}\_j$ and $\boldsymbol{h}\_j$

**Comment by JonathanSum** [comment]
Updated: I have improved a little bit on Chinese translation.
But the latex is not fixed yet. I will pick another day to find a way to fix them. 

Please feel free to pull this one only for a translation update.

**Review by Atcold — APPROVED** [review]
Thanks.
I can try to help fixing the LaTeX next week.

**Pull request merged**
