### PR TITLE
Lecture dates (for all languages), other fixes

### PR DESCRIPTION
**Pull request by jatinkhilnani**
- Fixed lecture dates and formats for all languages
- Author (10-1, 10-2)
- Redundant title (12-1)
- Image ref & other modifications (zh: 05-2)

### CODE REVIEW

**Comment by ebetica** [comment]
This is amazing! Thank you so much!

I wonder if we want to use `dd/mm/yyyy` as the date format to be readable across languages? (shouldn't block this PR)

**Comment by jatinkhilnani** [comment]
I believe `mon` format is more readable because it does not cause the confusion of `dd/mm` vs `mm/dd` based on what the audience is used to or assumes it to be.

**Comment by jatinkhilnani** [comment]
Verified that this is related to PR #335 which got synced to my fork through 3bec78ac110d3d4e30c4d8eb47832da7cabf33d4. Related to emoji changes done by @ebetica. Should not be a problem as the referenced PR is already merged.

**Comment by jatinkhilnani** [comment]
Verified that this is related to PR #335 which got synced to my fork through 3bec78ac110d3d4e30c4d8eb47832da7cabf33d4. Related to flag icon changes done by @ebetica. Had an opposite effect on my end of undoing his changes, even though `jekyllbook` submodule was synced. Checking how the effect can be reverted.

**Comment by jatinkhilnani** [comment]
Verified that this is related to PR #335 which got synced to my fork through 3bec78ac110d3d4e30c4d8eb47832da7cabf33d4. Related to flag icon changes done by @ebetica. Had an opposite effect on my end of undoing his changes, even though `jekyllbook` submodule was modified but not synced correctly. Forced it to be in sync so that the modifications are not reverted. Please merge now.

**Pull request merged**
