### PR TITLE
[FA] Translation of 06.md and 06-1.md

### PR DESCRIPTION
**Pull request by Alireza1044**

### CODE REVIEW

**Comment by SMMousaviSP** [comment]
Isn't it better to translate part A, part B to بخش الف, بخش ب ?

**Comment by Alireza1044** [comment]
> Isn't it better to translate part A, part B to بخش الف, بخش ب ?

You're right. I'll change it in the next commit.

**Comment by anasselhoud** [comment]
> > Isn't it better to translate part A, part B to بخش الف, بخش ب ?
> 
> You're right. I'll change it in the next commit.

@Alireza1044  You can change it now and it will get updated and merged directly with your current PR.

**Comment by Alireza1044** [comment]
> > > Isn't it better to translate part A, part B to بخش الف, بخش ب ?
> > 
> > 
> > You're right. I'll change it in the next commit.
> 
> @Alireza1044 You can change it now and it will get updated and merged directly with your current PR.

Yeah I know I'm just waiting for the reviewer, I'll apply the changes after that.
Thanks btw.

**Review by Atcold — APPROVED** [review]
Great, awesome!
Thanks!

**Pull request merged**
