### PR TITLE
update 05-3 lab notes

### PR DESCRIPTION
**Pull request by wtao0221**
we have revised the notes according to the latest feedback.

### CODE REVIEW

**Comment by Atcold** [comment]
@wtao0221, just to confirm, this closes #90. Correct?

**Comment by Atcold** [comment]
Screenshot 2020-03-02 23 56 57
One more PR, plz.

**Comment by Atcold** [comment]
I fixed a few things myself https://github.com/Atcold/pytorch-Deep-Learning/commit/0094ce440821bb0263420dfd14228caa100e5f1e.
Still, I need the missing image.

Good work, though.

**Comment by wtao0221** [comment]
Thanks. Please wait me seconds.

**Comment by wtao0221** [comment]
Yes. And please close #90.

**Comment by Atcold** [comment]
Closed. Thank you @wtao0221.

**Pull request merged**
