### PR TITLE
[IT] Week 8

### PR DESCRIPTION
**Pull request by marcozullich**
lecture 8 translations
[minor merge conflicts on week 05]

Note: from next translation/review on, I'll do a fetch upstream + rebase; for this time, I got the message too late unfortunately :/

### CODE REVIEW

**Comment by Atcold** [comment]
Marco, don't get mad, but you need to learn how to use git and GitHub.

Screenshot 2020-05-18 at 14 40 46

This is not okay… You need to update your local repo to whatever is the state of `upstream`.
Or, if you don't want to learn, just fork it every time you want to sync (which is brainless, but works).

**Comment by Atcold** [comment]
Here a few references:
 - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
 - https://www.atlassian.com/git/tutorials/git-forks-and-upstreams

**Comment by Atcold** [comment]
What shall we do with this PR?

**Comment by marcozullich** [comment]
Yeah, it's replaced by #339, I'm closing it

**Comment by Atcold** [comment]
Oh, okay, perfect.
Just as a note, you can simply force push the same branch in order to overwrite an older PR. In this case there is no need to create a new one.
Anyhow, I hope you've been enjoining learning *git* and GitHub.

**Pull request closed without merging**
