### PR TITLE
[FR] Translations of weeks 1 to 12

### PR DESCRIPTION
**Pull request by lbourdois**
Hi Alfredo,

Here are the French translations of the first 3 weeks ! 
With Yann's feedbacks to take into account I saw a bit too big to add the 14 weeks at once (about 100 to 120 pages of Markdown pages to be still reread :sweat_smile: ).  
So the rest will arrive progressively during the next week.
Hopefully everything will be good

Loïck

### CODE REVIEW

**Comment by lbourdois** [comment]
Added weeks 4 to 12 taking into account Yann's feedbacks.

The translation of week 13 doesn't suit me (it was done before the videos were put online, and it's a subject I've never seen during my studies or professionally so I'm afraid I made a translation mistake), I have to do it again.
Week 14 has been translated, only two paragraphs are missing based on ideas developed in week 13, so I will add week 14 once week 13 has been translated again.

**Review by Atcold — APPROVED** [review]
A-M-A-Z-I-N-G-!

**Comment by Atcold** [comment]
You need to translate `docs/fr/index.md` and `docs/fr/README-FR.md` as well.
I'm adding your contribution to `docs/_config.yml` as well, and you should update it when you push the latest files.

Thank you again so much for this AMAZING PR!

**Comment by Atcold** [comment]
There were some issues with `{{{` in some files.

```
"{{{site.baseurl}}" in fr/week05/05-3.md 
"{{{site.baseurl}}" in fr/week08/08-2.md
"{{{site. baseurl}}" in fr/week08/08-2.md           
"{{{site.baseurl}}" in fr/week08/08-3.md
"{{{site.baseurl}}" in fr/week09/09-2.md
"{{{site.baseurl}}" in fr/week10/10-3.md
"{{{site.baseurl}}" in fr/week10/10-3.md
```

**Comment by Atcold** [comment]
There are some more broken things. Compare:

 - https://atcold.github.io/pytorch-Deep-Learning/fr/week02/02-2/
 - https://atcold.github.io/pytorch-Deep-Learning/it/week02/02-2/

**Comment by lbourdois** [comment]
The README-FR file will arrive with the translations of weeks 13 and 14.

Then I plan to write the Github Wiki for French to indicate the choices that were made for the translation. That way in index.md, I will add a small sentence referring to this wiki in the paragraph I plan to add as indicated by email a few days ago.

But before all that, I'm going to do a new PR to fix the problems in the files already online.
For translations I use DeepL to have a first base to proofread and that I don't have to retype everything by hand. It also has the advantage of offering a glossary to indicate that for a given word, I want a specific translation and not another. Also, the text produced probably fewer spelling mistakes than I could produce.
The downside is that it usually breaks the Markdown presentation, producing errors as you pointed out. I've fixed a lot of them, but I hadn't noticed the problem with the 3 {{{ :open_mouth:

**Pull request merged**
