### PR TITLE
[IT] Translation of 06-1

### PR DESCRIPTION
**Pull request by synchro--**
- created dir week06 for italian translation 
- added translation of 06-01 italian module, at `/pytorch-Deep-Learning/docs/it/week06/06-1.md`
- added new two files 06-2, 06-3 but still WIP (empty in this PR)

### CODE REVIEW

**Comment by Atcold** [comment]
I guess it's not yet ready for merging, right?

**Comment by synchro--** [comment]
06-1.md is reviewable. The others are wip.

As you prefer, I guess if you want to merge only when the whole 06 week is ready then yep, wait for the other two.   
If instead you want to merge them as soon as they are ready I can open an MR for each of them, no problem for me.

**Comment by Atcold** [comment]
Yeah, I can merge this, right now.
You need to update the `_config.yml`, and, ideally, remove the empty files you've created.

**Comment by synchro--** [comment]
Will do ASAP.

**Comment by Atcold** [comment]
Thanks!

**Pull request merged**
