### PR TITLE
Week15-2 markdown commit

### PR DESCRIPTION
**Pull request by billxbf**
Fixed typo and grammar
Modified alignment and image reference

### CODE REVIEW

**Review by Atcold — APPROVED** [review]
Thanks! Merging now. Then checking for issues 😬

**Comment by Atcold** [comment]
Oops, you forgot to update `docs/_config.yml`.

**Comment by Atcold** [comment]
Replace every `$y$` with `\vect{y}$`.
The differential `dz` is typed as `$\mathrm{d}z`.
Fix the following (use `\texttt` and proper formatting):
image

`hinge` should go inside `\text{}`, `.` should be replaced with `\cdot`.
image

It looks like the third scriber has a good grasp of LaTeX. Feel free to collaborate on these fixes.

**Comment by Atcold** [comment]
Moreover, you need to update `index.md` and `15.md` as well.

**Comment by billxbf** [comment]
Got it, I'll fix these issues tonight.

**Comment by Atcold** [comment]
Thanks!

**Pull request merged**
