### PR TITLE
[zh]fix of 02.2 and 02.3

### PR DESCRIPTION
**Pull request by Tangshengku**
Fixed 02-3 and 02-2.md is what I have reviewed.

### CODE REVIEW

**Comment by Atcold** [comment]
This commit attempts to remove `5-1.md` from the repository.
Also, you cannot change the name of the files. You have to use the original names.
The website doesn't understand new names.

Screenshot 2020-04-25 at 22 42 07

**Comment by Atcold** [comment]
Here you're editing the `_config.yml` file, and removing things about week 05.

Screenshot 2020-04-27 at 23 21 23

And here you're removing chapter `05-1`.

Screenshot 2020-04-27 at 23 21 41

You need to use the **same names**. You cannot call them `Fixed-something`. These files need to replace the previous versions, and therefore have the **same** name.

**Comment by Atcold** [comment]
@ebetica, can you plz help us out here?

**Comment by Tangshengku** [comment]
> call

image
When I try to change its name, I get error.

**Comment by Atcold** [comment]
Yes, that's an option too.
Fork my repo first (so you get the latest version).
Then upload whatever contribution you have, overwriting the previous files.
Then send a PR.

Closing this one for now.

**Pull request closed without merging**
