### PR TITLE
Finish translating 02-3.md

### PR DESCRIPTION
**Pull request by titusjgr**

### CODE REVIEW

**Comment by Atcold** [comment]
@titusjgr, great job! Thanks!

@ebetica, can you plz squash-merge this PR? Thanks!

**Comment by ebetica** [comment]
Hey @titusjgr, did you mean to include the translations for 01-3.md in here as well? Is that chapter finished?

Also - did you include the changes from #108 in here as well? I noticed the image links were from before that patch.

**Comment by titusjgr** [comment]
@ebetica, I accidentally included 01-3.md so please ignore it.

And I didn't notice the change of image.  Could you change it to the correct link?

**Comment by ebetica** [comment]
@titusjgr hey I am fixing it and merging. Please give it a quick look through to make sure I did not lose any work of your by accident.

**Pull request merged**
