### PR TITLE
[IT] week 05 lectures 2 and 3

### PR DESCRIPTION
**Pull request by marcozullich**

### CODE REVIEW

**Comment by Atcold** [comment]
There are 32 commits here!
What's going on???

**Comment by marcozullich** [comment]
I had to commit and push often since I'm working on multiple PCs

**Comment by Atcold** [comment]
I don't understand what's going on.
The title says "week 03, lecture 2 and 3".
And then I see this:

Screenshot 2020-04-27 at 22 53 34

Which is week 05, lecture 2 and 3.

**Comment by marcozullich** [comment]
Argh, this is because I merged everything into master *before* the PR was merged, actually merging all future files as well... I'm closing this one, I'll create a new PR only with the relevant files...

**Comment by marcozullich** [comment]
No, actually, after review, the title of the PR is wrong! I corrected it

**Comment by marcozullich** [comment]
I'm closing the PR since everything got a little too mixed up bc I merged from my master, which I shouldn't have done since it carried on other modifications not relevant to the title of the PR. Hence, this PR is now replaced by #283

**Comment by Atcold** [comment]
Sweet.

**Pull request closed without merging**
