### PR TITLE
[DLFL22] Rephrase \beta description in week 7 

### PR DESCRIPTION
**Pull request by pscollins**
"More fluctate" is somewhat difficult to parse.

### CODE REVIEW

**Comment by Atcold** [comment]
I have no idea what "fluctuate" means…

**Comment by pscollins** [comment]
Would something like "greater variance" be more precise? Or even just "less smooth"? 

I think the original, "more fluctuate model," is a bit difficult to follow. The direct fix, "more fluctuating model," I find hard to interpret -- I'm not clear if it means that the ripples in the surface have a higher amplitude or a higher frequency. My understanding is that it's really talking about frequency -- more ripples, but the maximum height of any ripple is not necessarily larger -- which is why I suggested "a model that fluctuates more."

**Comment by Atcold** [comment]
Since what the student wrote about this section makes no sense, I've gone back to Yann's lecture recording.

[image](https://youtu.be/tVwV14YkbYs?t=1853)

The caption reads as follow:

> 0:30:53.400,0:30:55.400
> The β parameter is kind of arbitrary
> 
> 0:30:55.690,0:31:00.450
> It's the way you calibrate your probabilities as a function of your energies, so
> 
> 0:31:01.030,0:31:06.660
> The larger the β, the more sort of binary your probability will be for a given energy function
> 
> 0:31:08.710,0:31:12.270
> If β is very very large, it is basically just the
> 
> 0:31:13.180,0:31:14.860
> the E(x,y)
> 
> 0:31:14.860,0:31:20.640
> for the y that produces the lowest energy that will have high probability and everything else will have very low probability and
> 
> 0:31:20.980,0:31:26.159
> For small β for a small β then you get kind of a smoother distribution
> 
> 0:31:26.680,0:31:28.390
> Okay
> 
> 0:31:28.390,0:31:32.099
> Β in physics terms is akin to an inverse temperature
> 
> 0:31:33.310,0:31:36.900
> Okay, so the β goes to infinity is equal to zero temperature

**Comment by pscollins** [comment]
How about this? I changed it to talk about argmax explicitly.

**Review by Atcold — APPROVED** [review]

**Comment by Atcold** [comment]
Thanks!

**Pull request merged**
