### PR TITLE
Farsi Translation

### PR DESCRIPTION
**Pull request by jemappelleMarie**
08.md and 08-1.md have been translated to Farsi (Persian).

### CODE REVIEW

**Review by Atcold — CHANGES_REQUESTED** [review]
Please, **don't add Persian to the English transcript**. You need to create **new files** in the `docs/fa` directory. For example the file `docs/fa/week08/08-1.md` will have commented English while it will show the Persian translation. Moreover, check out the [translation guidelines](https://github.com/Atcold/pytorch-Deep-Learning/wiki/Translation-Guidelines).
You have to update `docs/_config.yml` as well, reflecting the new added content.

**Comment by Atcold** [comment]
Hello?

**Comment by jemappelleMarie** [comment]
HiYeah, sure. Sorry. I got it, I apply the changes asap.Sent from my Galaxy
-------- Original message --------From: Alfredo Canziani <notifications@github.com> Date: 25/11/2020  07:11  (GMT+03:30) To: Atcold/pytorch-Deep-Learning <pytorch-Deep-Learning@noreply.github.com> Cc: Mariiie <m_kh.8867@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [Atcold/pytorch-Deep-Learning] Farsi Translation (#679) 
Hello?

**Comment by Atcold** [comment]
Great, thanks!

**Pull request closed without merging**
