### PR TITLE
[EN] Fix timers

### PR DESCRIPTION
**Pull request by lbourdois**
Voila

### CODE REVIEW

**Review by Atcold — APPROVED** [review]
Thanks!

**Comment by Atcold** [comment]
Can you say once again what did you actually fix?
I'm not sure I understood.

**Comment by lbourdois** [comment]
Here is an example where the timers overlap :

0:00:00.000,**0:00:05.339**
last time we have seen that a matrix can

0:00:02.550,0:00:10.559
be written basically let me draw here

**0:00:05.339**,0:00:12.719
the matrix so we had similar roles right


So with the little python scrip I apply, it becomes : 

 0:00:00.000,0:00:05.339
last time we have seen that a matrix can be written basically let me draw here

0:00:05.339,0:00:12.719
the matrix so we had similar roles right and then we multiplied usually design by

Does that make sense?

**Comment by Atcold** [comment]
Oh, I didn't notice there was some overlap.
What was the effect on YouTube?

**Comment by lbourdois** [comment]
I don't know what the effect is on YouTube.

What I noticed is that you added the sbv files in two steps. First the weeks 1 to 5. Then in a second time all the others.

The files of weeks 1 to 5 did not contain any overlaps when you added them. The others did.

When you watch on YouTube, for most of the videos, there are only the subtitles generated in English available. Since this is intrinsic to YouTube, there is no problem with subtitles.

For the few videos where the corrected English is available (for example the video lecture01 or the video practinum 01), the rendering is good. But as said above, these are files where there was no overlap at the beginning. 

So I don't know what is the impact of overlaps on YouTubebecause no English file corrected with overlap has been added on your channel. And unless I forgot, all the files that contained overlaps are now corrected.

But the sbv files of practinums 14 and 15 are not available in the github directory. If when you add them you find overlaps, you could test the impact on YouTube is and we would have an answer to your question :D

**Comment by Atcold** [comment]
Thanks for pointing that out.
78aef4527a99e40a2d93505ce4625b64a4e1c8cd

**Comment by lbourdois** [comment]
What happened between two episodes of The Queen's Gambit ? : #725 👀

**Comment by Atcold** [comment]
Two episodes of what?!

**Comment by lbourdois** [comment]
A Netflix mini-series about a chess champion in 7 episodes.
I don't know if there is a sequel or not, I only watched the first 3 episodes last night, so I don't know if the end is closed or open.
This series worked quite well a month and a half ago in France at the beginning of the second confinement. A lot of people have downloaded applications to learn how to play chess, watch videos on youtube, press articles, etc..
So I thought maybe I need to watch this.

**Pull request merged**
