### PR TITLE
Fixed week-11-1 RRelu image

### PR DESCRIPTION
**Pull request by nhuang37**

### CODE REVIEW

**Comment by Atcold** [comment]
I'm confused. This PR does nothing?

**Comment by nhuang37** [comment]
Hi Alf, I amended the name of RReLU picture so it could show at week-11-1.
Could you check and see if it works? Thanks!

**Comment by Atcold** [comment]
You didn't commit 😛 
This is all I see.

Screenshot 2020-05-11 at 23 52 44

**Comment by nhuang37** [comment]
Just updated another commit. Can you try whether this works? Thanks Alf!

**Pull request merged**
