### PR TITLE
[KR] Translation of 11-2 & 11-3 complete

### PR DESCRIPTION
**Pull request by choongheelee**
11-2 & 11-3 complete.

Sorry it took so long, guys. I had circumstances about application for job positions, so I couldn't finish them earlier.
I apologize that and thank you all.

### CODE REVIEW

**Comment by Atcold** [comment]
@skyil7, please review.

**Comment by Atcold** [comment]
@skyil7, any update?

**Review by skyil7 — APPROVED** [review]
Everything looks fine! Thank you for contribution and sorry for the late review.

**Comment by skyil7** [comment]
I thought SeungHeon already reviewed this one. (Because of the wiki)

**Comment by Atcold** [comment]
You've been merging the [KO] PRs. So, I left it for you 😜

**Comment by Atcold** [comment]
I don't see the edits to `docs/_config.yml`.
Please, edit the file accordingly.

**Pull request merged**
