### PR TITLE
[ZH] updating the index.md

### PR DESCRIPTION
**Pull request by JonathanSum**
Adding the missing week5.
I don't know how to fix this missing picture issue. I suggest someone should fix it.
image

### CODE REVIEW

**Comment by Atcold** [comment]
I fixed that right now.

**Comment by JonathanSum** [comment]
Thx for fixing

**Comment by JonathanSum** [comment]
image

**Comment by Atcold** [comment]
I've removed it myself.
You've added a `_config.yml` file to the main repo (not even the `docs/` folder, see https://github.com/Atcold/pytorch-Deep-Learning/pull/427/commits/1be18a440c8b99237ca24d4de7ce9c513d794d91) with inside `theme: jekyll-theme-merlot`. You can check the diff.

**Pull request merged**
