### PR TITLE
Update 08-1.md

### PR DESCRIPTION
**Pull request by Florence2Me**

### CODE REVIEW

**Comment by Atcold** [comment]
I've already merged 08-1. What is this?

**Comment by Florence2Me** [comment]
Hi Alfredo,

I modified 08-1.md as follows:

   - Replace figure 4 with actual math.
   - Set width="50%" for fig 1 and 2.
   - neg should be \text{neg}.
   - non math F in the picture below.

[image: Screenshot 2020-03-28 20 35 31]
<https://user-images.githubusercontent.com/2119355/77837148-b7414400-7133-11ea-9744-dde465d5a0e4.png>


Best,

Shuya

**Comment by Atcold** [comment]
@Florence2Me…
You changed the aspect ratio of the images.
You pushed all the edits again. I did already merge your previous contribution.
You were supposed to rebase on upstream `master` branch.
I fixed it myself.

**Comment by Atcold** [comment]
No math is showing…
I cannot waste my time fixing broken stuff…

Screenshot 2020-03-30 00 38 36

**Comment by Atcold** [comment]
Run the website locally and make sure the formula actually shows.
Thanks.

Screenshot 2020-03-30 00 39 21

**Comment by Florence2Me** [comment]
Hi Alfredo,

I made a new PR. I changed the title and formula in 08-1.md.

Many thanks,
Shuya

**Comment by Atcold** [comment]
Yup, saw that.
Thanks!

**Pull request merged**
