### PR TITLE
Update 03.md

### PR DESCRIPTION
**Pull request by fg746**
Traduzione "kernel"

### CODE REVIEW

**Comment by Atcold** [comment]
I don't understand why.

**Comment by fg746** [comment]
I changed it after this was discussed on the italian-translation slack channel. Some of us thought this would be the least confusing, since filter was being used in the context of input/out channels in later weeks.

**Comment by Atcold** [comment]
Right, they are synonyms. They both translate to *filter*.

**Comment by fg746** [comment]
Sure. It is a little bit confusing but I guess that's true in English, as well. I'll post on Slack to keep "filtro" for both.

**Comment by Atcold** [comment]
Thanks.

There are very many bugs and errors already.
Let's focus on them, instead. Hehe.

**Pull request closed without merging**
