### PR TITLE
[ES] Possible fix to #259

### PR DESCRIPTION
**Pull request by LecJackS**
Removed all "es/" from links, so they point correctly to each page.

"Possible" because I don't know if that's how the site is generated, but in case it is, can be solved as soon as possible.

(Can do it for other langs if needed)

### CODE REVIEW

**Comment by LecJackS** [comment]
Two different PRs got merged into this one. First is for index fix, second is translation [ES] and typos [EN] for Week 6, part 3.

**Comment by Atcold** [comment]
This was fixed in #263, right?
I'm confused now.

**Comment by LecJackS** [comment]
> This was fixed in #263, right?
> I'm confused now.

Sorry about that, two PRs got merged together.

1. One is already solved by #263 , so I updated the first PR to match #263 so it has no effect.
2. The other is a translation for [ES] 06-3, and review of [ES] 01-3 (not my translation, but my corrections to it)

**Comment by Atcold** [comment]
Can you please rebase on top of `master`?
In this way I'm merging only your contribution (the [ES] fixing).

**Comment by LecJackS** [comment]
> Can you please rebase on top of `master`?

Yes! I'll do it now, have little to no time these past days.

**Comment by LecJackS** [comment]
Closing this, so I can fork again and copy modified files (I don't know how to rebase from here).

**Comment by Atcold** [comment]
Okay 😄

**Pull request closed without merging**
