### PR TITLE
[FR] website V2 (part 1)

### PR DESCRIPTION
**Pull request by lbourdois**
Hi  @Atcold 👋,

 This PR contains : 

- some corrections for the YouTube subtitles 🎥 
(corrected a z-tilde in the subtitles of practinum 15A following your correction in the English file in the PR #796 + some corrections in lecture 14). Everything is ok now for this point. The translation of the video titles is available in response to the PR #796.

- a modification of the images of the site consisting mainly in cropping them 🖼 
(white bands appeared for some images when using the dark themes of the site, it should be cleaner now).

- the first part of the V2 site in French 🇫🇷
This first part focuses on the form. I have for example italicized all the English terms that can't be translated into French, harmonized the legends of the figures, corrected some markdown formulas that were broken, paragraphs present in English in the French files because they were badly commented, etc.
The second part of V2 (which if everything goes well will be the last and ultimate PR closing the work on the French translation 🥳) will consist in adding the FAQ that we had mentioned on Discord, checking if part 1 of V2 is OK and a review to remove possible spelling/conjugation mistakes.

Loïck

### CODE REVIEW

**Review by Atcold — APPROVED** [review]

**Comment by Atcold** [comment]
Awesome job. Thank you so much, @lbourdois! ❤️❤️❤️

**Comment by Atcold** [comment]
So, you've added copies of the current images with a lower case extension.
Now, there are both version in the repo, but this is creating issues on machines that are case insensitive.

image

image

**Comment by lbourdois** [comment]
Argggg sorry, I didn't have this problem with my machine so I didn't see it :(((

I saw that you removed some images, is everything ok now or are there still things to correct?

**Comment by Atcold** [comment]
I've removed all images with low case extensions copies of the corresponding upper case ones.
If you check all MD files, the upper case versions are used and linked (you can see this also by right-clicking on an image and choosing open in new tab, you'll see the upper case extension).

**Pull request merged**
