### PR TITLE
Week 13 Section 1.

### PR DESCRIPTION
**Pull request by sherlynchan**

### CODE REVIEW

**Comment by Atcold** [comment]
Really good job! Can you expand the captions a little? There's only a title, right now? (Notice I've updated your file, so you need to fetch `upstream`.)

**Comment by sherlynchan** [comment]
Hi Alf,
Sorry but I don’t get your point, could you please explain what captions needed to be expanded?
Thanks,
Shaoling

**Comment by Atcold** [comment]
Right now there's only a title. The caption (brief explanation of the image) is missing, I think.

**Comment by sherlynchan** [comment]
Ok I see! 
Thanks!:)
Shaoling

**Comment by sherlynchan** [comment]
Hi Alf,

Please check here about the update.
https://github.com/Atcold/pytorch-Deep-Learning/pull/306 <https://github.com/Atcold/pytorch-Deep-Learning/pull/306>

Thanks,
Shaoling

**Pull request merged**
