### PR TITLE
Spanish translation of README.md and index.md.

### PR DESCRIPTION
**Pull request by LecJackS**
Also found a typo on original index.md (en) on Yann LeCun's name (as "Yann LeCuna"). Or maybe he likes to be called like that :P

### CODE REVIEW

**Comment by ebetica** [comment]
Cool! I believe you have to modify the `_config.yml` file accordingly and add a spanish section. (`es`, right?)

**Comment by ebetica** [comment]
@Atcold the Chinese and Korean translations do not contain a "People" section in the home page. Is that expected?

**Comment by LecJackS** [comment]
@ebetica Thank you! and Done! 

About the "People" section, I translated EVERYTHING in those files, just in case. But let me know if it's not required and I need to remove it.

**Comment by Atcold** [comment]
The Mandarin translation is behind with the `index.md` translation.
I think for the translated version we can leave the graders out.

**Comment by Atcold** [comment]
Can we shrink the titles? They are impossible to read on a phone.
They don't have to be "too" correct. Just one or two words.

Screenshot 2020-03-24 23 01 55
Screenshot 2020-03-24 23 02 06

**Comment by Atcold** [comment]
"SGD y retroprop" es suficiente, por example.

**Comment by Atcold** [comment]
Es "entrenar" o "adriestar"?
En italiano usamos el secundo termine.

**Comment by LecJackS** [comment]
> Es "entrenar" o "adriestar"?

Es "entrenar". "Adiestrar" is only used for animals, like "adiestrar un perro". (I can't think in any other use for it now, maybe "adiestramiento militar").

"Entrenar" is widly used for NNs, and is also use for physical training, and maybe some kind of mental practice, like "training the mind in for some discipline".

**Comment by LecJackS** [comment]
@Atcold Give me a couple of minutes to discover how to update/fetch the repo fork and will PR again the titles shortened.

**Comment by Atcold** [comment]
@LecJackS, aquí hai una guida https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request merged**
