### PR TITLE
Week 5 - Lab

### PR DESCRIPTION
**Pull request by AngelaZZZ-611**
05-3.md is the lab notes, and directory 05-3 contains the pictures included.

### CODE REVIEW

**Comment by AngelaZZZ-611** [comment]
05-3.md is the lab notes, and directory 05-3 contains the pictures included.

**Comment by Atcold** [comment]
You need to update `05.md` and `_config.yml`!
Doing this for you...

**Comment by Atcold** [comment]
Replace all handwritten formulas with LaTeX.
Replace all screenshots of code with actual code snippets.

**Comment by Atcold** [comment]
Basically, replace **ALL** figures from 5 to 18.

**Comment by Atcold** [comment]
Fig 9 actually include the output figure, not a screenshot, plz!

**Comment by Atcold** [comment]
Fig 5 include code, not a screenshot!

**Comment by Atcold** [comment]
Figures 1–4 should be drew with https://www.mathcha.io/

**Pull request merged**
