### PR TITLE
[MISC] Add lecturer, dates, and translators

### PR DESCRIPTION
**Pull request by ebetica**
Example:

image

image

I did not check whether all the authors were correct / up to date, and if somebody misspelled an annotation it won't appear.

### CODE REVIEW

**Comment by Atcold** [comment]
This is great! Can we add the translated by field too?
Shall I merge this for now?

**Comment by Atcold** [comment]
Okay, merging, because it's too awesome!

**Comment by Atcold** [comment]
Bug! Haha.
Screenshot 2020-05-22 at 21 06 01

**Comment by Atcold** [comment]
Can we remove the default to `Yann LeCun`?

**Comment by ebetica** [comment]
Okay - let me clarify before I start implementation:

- No lecturer on summaries page
- Translated By if it exists
- Remove the emoji if there's no scribe annotations
- What about the date? Do we date the summary pages too or not?
- If no (Date, Translated-By, Scribe) annotations, remove the line.

**Comment by jatinkhilnani** [comment]
Quick query: The section dates now don't seem to align with lecture date, e.g. 13-1 & 13-3 say 5-May, while 13-2 still reflects the lecture date 27-Apr. Are they being updated to reflect edits?

**Comment by ebetica** [comment]
@jatinkhilnani I think they should line up with lecture dates, but I guess we have not been checking them prior. I don't think we've standardized on a date format either... Maybe send in a PR if you find an error and know the real lecture date?

**Comment by jatinkhilnani** [comment]
@ebetica One PR #340 coming right up. Have modified lecture dates and format across all languages and made some other fixes too. 

Had to change the lecture dates manually across all language markdowns. I believe we can add the lecture plan to config and have it take from there, so that all markdowns remain in sync automatically even for future translations. What say?

**Comment by ebetica** [comment]
Are the dates consistent across languages? Should we use Chinese words instead of 3-let month abbreviations? Also - are lecturer names consistent across languages? Should we use the Chinese version of a Chinese lecturer's name on the Chinese translations, for example? It might be better to leave it as is, in order to be flexible.

**Comment by jatinkhilnani** [comment]
Yes, the dates & lecturer names are consistent for all languages. They would be carried forward to other languages for future translations, since the `en` files would be used for translation. Hence, including them in the default configuration as had suggested earlier is not required for now.

If translating name & date characters, each translator would have to be consistent for each language, to do so for lecturer, contributor & translator names and corresponding dates.

**Comment by Atcold** [comment]
> Okay - let me clarify before I start implementation:
> 
> * No lecturer on summaries page
> * Remove the emoji if there's no scribe annotations

Yeah, these two are the same. Summaries do not have authors (or have too many), so I'd avoid the emoji and bottom line.

> * Translated By if it exists

Yup.

> * What about the date? Do we date the summary pages too or not?

Date = when we had a given lecture. Summaries do not need dates.

> * If no (Date, Translated-By, Scribe) annotations, remove the line.

If there is no `Authors` field, then no line and no meta data.

**Comment by JonathanSum** [comment]
I just make a comment here.

I think the best way to earn credit from doing this work is not by having the ability to write my name on the translator's name. 

It is I am able to build a **successful** energy-based model or something more advance from this course.

**Pull request merged**
