### PR TITLE
[EN] change wording on face detection false positives section

### PR DESCRIPTION
**Pull request by fguiso**

### CODE REVIEW

**Comment by Atcold** [comment]
I'm confused. This seems Italian stuff.

image

**Comment by fguiso** [comment]
I tried the "cherry-picking" but the old commits still seem to be here 😬
I can just create a new branch for these English edits.

**Comment by Atcold** [comment]
This should fix it. Can you try?

```
git checkout en-week06
git reset --hard 7309acf2
git cherry-pick 88abf00
git push -f
```

Also, you can copy and paste here what you type and what the terminal responds with.
So, I can figure out what's going on.

**Comment by fguiso** [comment]
It worked! Thanks 1000

**Pull request merged**
