### PR TITLE
[AR] Translation of README-AR.md

### PR DESCRIPTION
**Pull request by anasselhoud**

### CODE REVIEW

**Comment by Atcold** [comment]
I've just reviewed this here https://github.com/Atcold/pytorch-Deep-Learning/pull/472/files#diff-b2b3f5cd56e4bca50f4231cb4b4c5abc
Maybe you want to remove it from the other PR and leave it just here?

**Comment by Atcold** [comment]
I just merged the translation of `README.md`. What is this PR for?

**Comment by Atcold** [comment]
@anasselhoud, can you explain what happened, please?

**Comment by anasselhoud** [comment]
@Atcold It was just a mistake. You already merged the first PR. This was just a repetition.

**Pull request closed without merging**
