### PR TITLE
[EN] Fix timers

### PR DESCRIPTION
**Pull request by lbourdois**
A PR that fixes the timers of the sbv files that I couldn't correct in PR #660  to avoid conflicts.

I also took the opportunity to correct the few errors I caught when translating  the lecture10.

I also noticed that the sbv files of the practinums of weeks 14 and 15 were missing.

### CODE REVIEW

**Comment by lbourdois** [comment]
Some corrections following the translation of lecture 12. 
This lecture should probably be reviewed (more than some others that I could already translate and which was really clean). 
I tried to fill in the "[inaudible]" I could find, but there are still a lot of them. I'm really struggling with the Scottish accent :/

**Review by Atcold — APPROVED** [review]
Thanks, merging.

**Comment by Atcold** [comment]
Please, remove `practicum10.sbv`. A new version has been pushed.

**Review by Atcold — CHANGES_REQUESTED** [review]
Please, remove `practicum10.sbv`. A new version has been pushed.

**Comment by lbourdois** [comment]
@Atcold 
I had sent the timers correction to Maria on Slack to avoid the conflict. She told me that she would update her PR, it seems she forgot.
So instead of deleting the file, I modify it by integrating Maria's reviews.
Hoping that everything is good

**Comment by Atcold** [comment]
I don't know how to merge this PR. The whole file shows conflicts.

**Comment by Atcold** [comment]
Let's take off `docs/en/week10/practicum10.sbv` for now and merge the rest.
Then we can create a PR just for `practicum10.sbv`, okay?

**Comment by lbourdois** [comment]
I deleted the practinum10 file
If it's still not good, you can close this PR

**Review by Atcold — APPROVED** [review]
You cannot delete it. You have to check out the whatever previous version.
Now your PR is effectively trying to remove the file from the repository.

**Comment by lbourdois** [comment]
It comes to nothing, I close and reopen another PR.

**Comment by Atcold** [comment]
LOL, I can help you live, next time.
I have Git ninja skills! Haha!

**Comment by lbourdois** [comment]
When I use a unix terminal I never have a problem  but when I use git commands under windows, it screws up every time, I wouldn't know how to explain this sorcery.

**Pull request closed without merging**
