### PR TITLE
[AR] use right-to-left divs

### PR DESCRIPTION
**Pull request by mapmeld**
Not sure if this fits into the translation project or the rendered book roadmap, but adding some ```<div dir="rtl">``` blocks like this makes the README use a right-to-left layout for Arabic

### CODE REVIEW

**Comment by anasselhoud** [comment]
We should use it for all the files. Arabic is technically written from right to left. Thank you for adding that to the files.

**Comment by Atcold** [comment]
Please, open an issue, so that we can come up with a template to use for *all* the files.
We don't want to patch them manually. We can simply use `template: arabic`, or similar.

**Comment by mapmeld** [comment]
I'm thinking it might be more relevant for me to make a PR on the CSS files for the online book, and not focusing on how this README looks on GItHub Markdown. It can be painstaking tagging each paragraph

**Comment by Atcold** [comment]
Please, let's talk about this on an issue, not on a Pull Request.
The class website was made on purpose for this course, and we've been updating it many times.
So, let's put together all the info in an issue.

@mapmeld, can you take care of opening it?

**Pull request closed without merging**
