### PR TITLE
Optimization Techniques I 05-1

### PR DESCRIPTION
**Pull request by guptv93**
Goes over Gradient Descent, SGD and Momentum. Moved Images to a separate folder and tested the website locally.

### CODE REVIEW

**Comment by Atcold** [comment]
**WHERE ARE ALL THE FIGURES???**

**Comment by guptv93** [comment]
It seems like the .gitignore file has an entry with *.png, because of which the files didn't get added. Force adding and raising another pull request.

**Comment by Atcold** [comment]
Just with the figures. Not with the text (that I've already edited).

**Comment by guptv93** [comment]
Raised a different pull request.

**Comment by Atcold** [comment]
Yup, saw that.

**Pull request merged**
