### PR TITLE
[ES] Translation of 01-3.md 02.md 02-1.md 

### PR DESCRIPTION
**Pull request by juanmartinezitm**
Week01\01-3.md
Week02\02.md
Week02\02-1.md

### CODE REVIEW

**Comment by Atcold** [comment]
@juanmartinezitm, can you please reply?

**Comment by juanmartinezitm** [comment]
Hi Alfredo, you can keep the one that I submitted.

**Comment by Atcold** [comment]
@juanmartinezitm, can you actually reply?

**Comment by Atcold** [comment]
File `01-3.md` has already been updated.
You cannot edit one file and submit another one in the same PR.
I have no idea which `01-3` is correct and which one is wrong.

Please, submit `01-3` separately.

**Pull request closed without merging**
