### PR TITLE
[DLSP21] Update 11-2.md and 15-2.md

### PR DESCRIPTION
**Pull request by rahuja123**
[DLSP21] Corrected equations in 11-2.md and deleted an inconsistent line  "Covered in section 2", but there was no section 2 on the page 15-2.md

### CODE REVIEW

**Comment by Atcold** [comment]
What was wrong with the equation? I cannot really tell the difference.
Also, can you please propagate your fix to all translations?
Thanks!

**Comment by rahuja123** [comment]
Sure, I will propagate for all translations.
When I was reading the blog, the equations aren't coming to be in the right format. If you look at 11-2.md, hinge loss and cosine embedding loss are not formatted right. 

image
**

**Comment by Atcold** [comment]
Cool.
It looks like the [Italian version](https://atcold.github.io/pytorch-Deep-Learning/it/week11/11-2/) got it right. You can copy and paste that.

**Comment by rahuja123** [comment]
Done. I am unable to verify locally due to some GEM and Jekyll version issue. I will try again to install them correctly and verify.

**Review by Atcold — APPROVED** [review]
Cool, awesome!

**Pull request merged**
