### PR TITLE
08-1.md update

### PR DESCRIPTION
**Pull request by Florence2Me**
Hi, I changed the title and formula. Please check it out.
Thx

### CODE REVIEW

**Comment by Atcold** [comment]
You need to rebase on top of `master`!!!

Screenshot 2020-03-30 01 48 31

**Comment by Atcold** [comment]
There is no formula!!!
Can you plz run the website locally and make sure it actually shows?

Screenshot 2020-03-30 01 50 53

**Comment by Atcold** [comment]
Okay, it works. Thanks!

**Comment by Florence2Me** [comment]
Cool.

**Pull request merged**
