### PR TITLE
[KR] 14.md, 14-1.md, and 14-2.md

### PR DESCRIPTION
**Pull request by marofmar**

### CODE REVIEW

**Review by Atcold — CHANGES_REQUESTED** [review]
We already have translated week 08 in Korean. Why are you adding these files?

image

**Comment by Atcold** [comment]
@skyil7, please review this PR.

**Comment by Atcold** [comment]
`git rm <file name>` should work, I guess.

**Comment by skyil7** [comment]
> `git rm <file name>` should work, I guess.

I will review this PR after this problem is solved.

**Comment by marofmar** [comment]
git rm done!

**Comment by Atcold** [comment]
Looks alright to me. @skyil7, plz review the content.

**Review by skyil7 — APPROVED** [review]
번역 수고하셨습니다. 별 문제는 없어보이니, 바로 머지하겠습니다!

**Review by skyil7 — APPROVED** [review]

**Comment by Atcold** [comment]
Great! Thank you both!

**Pull request merged**
