### PR TITLE
[AR] Translation of (02-1, 02-2, 02-3, 03-1, 07-1) + Review of (index, 01-3, 02, 03-2, 04-1, 05-2, 05-3, 06, 06-1, 06-2, 14-2)

### PR DESCRIPTION
**Pull request by hayaalsh**

### CODE REVIEW

**Comment by Atcold** [comment]
I have no idea what Git is doing. On it.

**Comment by Atcold** [comment]
I still have all the commits. I'm just not sure what happened.

**Comment by Atcold** [comment]
For reference https://support.github.com/ticket/personal/0/1214737.

**Comment by hayaalsh** [comment]
No worries, I guess the universe doesn’t want me to contribute to this repo 😝💔 let me know if I need to do anything from my side.
Also, the link you shared doesn’t work. Seems like a ticket to github which can’t be viewed by the public.

**Comment by Atcold** [comment]
I'm moving this PR to #785.
I'll provide feedback there, if any.

**Pull request closed without merging**
