### PR TITLE
[BN] Translation of week06-1 and homepage disclaimer

### PR DESCRIPTION
**Pull request by Tasmin153**
I have translated the homepage disclaimer and major portion of lecture 1 from week-6. (upto "A multi-scale face detection system" paragraph).   I will complete the rest portion asap.

### CODE REVIEW

**Comment by Tasmin153** [comment]
Week-6 Lecture-1 Completed until Semantic Segmentation.

**Review by Tasmin153 — COMMENTED** [review]
Week-6 Lecture-1 Completed for review.

**Comment by Atcold** [comment]
What happened here?

**Comment by Tasmin153** [comment]
I was facing some issues committing hence I had opened #764 pull request , added all the files in that request.

**Comment by Atcold** [comment]
Okay, great. I'm slowly coming back and checking out all contributions.
Thanks for your patience.

**Comment by Tasmin153** [comment]
No problem at all ! I'm happy to be able to contribute here.

**Pull request closed without merging**
